src/cdda-player.c: always use "%s"-style format for printf()-style functions
`ncuses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in palce of format
string when built with CFLAGS=-Werror=format-security:

    cdda-player.c:1032:31:
      error: format not a string literal and no format arguments [-Werror=format-security]
     1032 |         mvprintw(i_line++, 0, line);
          |                               ^~~~

Let's wrap all the missing places with "%s" format.